import { notFound } from "next/navigation";
import { store } from "@/server/store";
import { findEntity } from "@/server/lib/registryHelpers";
import { normalizeEvent, normalizeEntity } from "@/lib/normalize";
import { Breadcrumb } from "@/components/shell/Breadcrumb";
import {
  Card,
  MetricRow,
  MetricRowHeader,
  GuidanceTimeline,
  ReactionChart,
  ReactionRow,
  Panel,
  CatalystCard,
  FreshnessDot,
  SurprisePill,
  GuidanceMoveBadge,
} from "@/components/primitives";
import { TickerLogo } from "@/components/primitives/TickerLogo";
import { SourcesPanel } from "@/components/event/SourcesPanel";
import { VerdictNote } from "@/components/event/VerdictNote";
import { computeFreshness } from "@/lib/freshness";
import { fmtDate } from "@/lib/format";
import {
  groupOf,
  isDerivedMetric,
  metricGroupLabel,
  METRIC_GROUP_ORDER,
  type MetricGroup,
} from "@/lib/metricGroups";
import type { MetricEntry } from "@/lib/types";

interface Props {
  params: Promise<{ ticker: string; eventId: string }>;
}

// Event (Print) Detail. FE PRD §7.6.

export const dynamic = "force-dynamic";

export default async function EventDetailPage({ params }: Props) {
  const { ticker: rawTicker, eventId: rawEventId } = await params;
  const ticker = decodeURIComponent(rawTicker);
  const eventId = decodeURIComponent(rawEventId);
  const [entities, tickerEvents] = await Promise.all([
    store.readRegistry(),
    store.readEventsForTicker
      ? store.readEventsForTicker(ticker)
      : Promise.resolve([]),
  ]);
  const rawEntity = findEntity(entities, ticker);
  // Look up the event by id first. If not found, try period-based
  // resolution — event ids get regenerated by shard rewrites (dedup
  // merges, fiscal-offset reverts, ingests all mint new ids) but
  // period labels ("FY2026 Q1") are stable across rewrites. URLs may
  // arrive with either format:
  //   /s/AAPL US/e/evt-troyt6   ← id-based (canonical)
  //   /s/AAPL US/e/FY2026-Q1    ← period-based (rewrite-resilient)
  // The period form uses '-' between year and quarter for URL-safe
  // parsing; we normalize back to space when matching.
  let rawEvent = tickerEvents.find((e) => e.id === eventId);
  if (!rawEvent) {
    const normalizedPeriod = eventId.replace("-", " ").trim();
    rawEvent = tickerEvents.find((e) => e.period === normalizedPeriod);
  }
  if (!rawEntity || !rawEvent) notFound();
  // Every render below reads through the normalized shape — components
  // never see undefined/null arrays or containers.
  const entity = normalizeEntity(rawEntity)!;
  const event = normalizeEvent(rawEvent, entity);

  const freshness = computeFreshness(event.sources.capturedAt ?? event.eventDate);
  const isCatalyst = event.kind === "catalyst";
  const headline = event.metrics.find((m) => m.isHeadline);

  return (
    <div className="mx-auto max-w-[1800px] px-10 py-8">
      <div className="mb-5">
        <Breadcrumb
          crumbs={[
            { label: "Overview", href: "/" },
            {
              label: `${entity.displayName} · ${entity.ticker}`,
              href: `/s/${encodeURIComponent(entity.ticker)}`,
            },
            { label: event.period },
          ]}
        />
      </div>

      <header className="mb-8 flex items-start justify-between gap-6">
        <div className="flex items-start gap-4">
          <TickerLogo
            ticker={entity.ticker}
            name={entity.displayName}
            size={48}
          />
          <div>
          <div className="mb-3 mono-caption normal-case flex flex-wrap items-center gap-x-2 gap-y-1">
              <span>
                {isCatalyst ? "Catalyst" : "Earnings"} ·{" "}
                {event.timing ?? "unscheduled"} · {fmtDate(event.eventDate ?? event.scheduledDate)}
              </span>
              {event.sourceLink ? (
                <span>
                  {" · "}
                  Source{" "}
                  <a
                    href={event.sourceLink.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-brand-hi hover:text-brand-fg underline"
                  >
                    {event.sourceLink.kind === "filing"
                      ? "filing"
                      : "check the source"}
                    {" ↗"}
                  </a>
                </span>
              ) : null}
          </div>
          <h1 className="text-[32px] font-semibold leading-tight tracking-[-0.02em]">
            {event.period}
            {headline ? (
              <span className="ml-3 align-middle text-[16px] font-normal">
                <SurprisePill
                  surprisePct={headline.surprisePct}
                  hasActual={headline.actual?.value != null}
                />
              </span>
            ) : null}
          </h1>
          <div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-[12.5px] text-tx-mid">
            <span>
              <span className="font-mono text-tx3">Ticker</span>{" "}
              <span className="font-mono text-brand-fg">{entity.ticker}</span>
            </span>
            <span>
              <span className="font-mono text-tx3">Freshness</span>{" "}
              <FreshnessDot state={freshness} />
            </span>
            {event.guidanceMove ? (
              <span>
                <span className="font-mono text-tx3">Guidance</span>{" "}
                <GuidanceMoveBadge move={event.guidanceMove} />
              </span>
            ) : null}
          </div>
          {event.eventDate ? (
            <div className="mt-2">
              <ReactionRow points={event.reaction?.points ?? []} />
            </div>
          ) : null}
          </div>
        </div>
      </header>

      <div className="mb-6">
        <VerdictNote
          eventId={event.id}
          initial={
            typeof event.verdictNote === "string"
              ? event.verdictNote
              : event.verdictNote?.text
          }
        />
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-[1.4fr_1fr]">
        {/* Numbers panel */}
        {isCatalyst ? (
          <Panel eyebrow="Catalyst detail">
            {event.catalysts?.length ? (
              <div className="flex flex-col gap-3">
                {event.catalysts.map((c, i) => (
                  <CatalystCard key={i} catalyst={c} />
                ))}
              </div>
            ) : (
              <div className="text-[13px] text-tx-mid">
                Catalyst detail not yet on file.
              </div>
            )}
          </Panel>
        ) : (
          <div className="flex flex-col gap-4">
            {(() => {
              const buckets = new Map<MetricGroup, MetricEntry[]>();
              for (const m of event.metrics) {
                const isDerivedFact =
                  (m.actual as { derived?: boolean } | null)?.derived === true;
                const g = groupOf(m.key, isDerivedFact);
                const arr = buckets.get(g) ?? [];
                arr.push(m);
                buckets.set(g, arr);
              }
              return METRIC_GROUP_ORDER.filter(
                (g) => (buckets.get(g)?.length ?? 0) > 0,
              ).map((g) => {
                const rows = buckets.get(g)!;
                const isDerivedPanel = g === "derived";
                return (
                  <Card
                    key={g}
                    eyebrow={`${metricGroupLabel(g)} · ${event.period}`}
                  >
                    <MetricRowHeader />
                    {rows.map((m) => {
                      const isDerivedFact =
                        (m.actual as { derived?: boolean } | null)?.derived ===
                        true;
                      const derived =
                        isDerivedPanel ||
                        isDerivedMetric(m.key, isDerivedFact);
                      return (
                        <MetricRow key={m.key} metric={m} derived={derived} />
                      );
                    })}
                  </Card>
                );
              });
            })()}
          </div>
        )}

        <Panel eyebrow="Reaction">
          <ReactionChart
            points={event.reaction.points}
            benchmark={event.reaction.benchmark}
          />
          <div className="mt-4 flex items-center gap-4 font-mono text-[11.5px] text-tx-mid">
            <span>
              baseline{" "}
              <span className="text-tx">
                {event.reaction.baselineDate ?? "—"}
              </span>
            </span>
            <span>
              close{" "}
              <span className="text-tx">
                {event.reaction.baselineClose?.toFixed(2) ?? "—"}
              </span>
            </span>
            <span>
              timing <span className="text-tx">{event.timing ?? "—"}</span>
              <span className="text-tx3">
                {" "}
                · baseline follows{" "}
                {event.timing === "AMC"
                  ? "next session"
                  : event.timing === "BMO"
                  ? "event-day close"
                  : "—"}
              </span>
            </span>
          </div>
        </Panel>

        {!isCatalyst && event.guidance.length > 0 && (
          <Panel eyebrow="Guidance timeline" padded={false}>
            <GuidanceTimeline items={event.guidance} />
          </Panel>
        )}

        <div className="lg:col-span-2">
          <SourcesPanel event={event} />
        </div>
      </div>
    </div>
  );
}
